### PR TITLE
Added Typescript

### PR DESCRIPTION
**Pull request by colefriedlaender**
- Added tsconfig.json with `touch tsconfig.json`
- Add Typescript with `npm install --save-dev @types/react @types/node`

### CODE REVIEW

**Review by fre-ben — APPROVED** [review]
LGTM 🦝 👍

**Review by mewiemers — APPROVED** [review]
LGTM 👍

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by lmachens — COMMENTED** [review]
Good job, but I would rename the js files:

> You're now ready to start converting files from .js to .tsx and leveraging the benefits of TypeScript!.

https://nextjs.org/docs/basic-features/typescript

**Pull request merged**
