### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by colefriedlaender**
https://prettier.io/docs/en/install.html

### CODE REVIEW

**Comment by colefriedlaender** [comment]
-Installes prettier with `npm i -D prettier`
- Added prettierignore
- Added npm run prettify to format all code

**Comment by fgottesmann** [comment]
TYPO "Add(d)ed npm run prettify to format all code" :)

**Review by fgottesmann — COMMENTED** [review]
Good Job! :)

**Review by ShiningElektra — COMMENTED** [review]
lgtm 👍

**Pull request merged**
